# Generated by Django 5.0.1 on 2024-03-14 19:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Представление в URL')),
                ('annotation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Содержимое поста')),
                ('picture', models.ImageField(blank=True, upload_to='posts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Изображение')),
                ('status', models.CharField(choices=[('PUBLISHED', 'Опубликовано'), ('DRAFT', 'Черновик')], default='DRAFT', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликован')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='Зафиксирован')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_posts', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
