# Generated by Django 5.0.1 on 2024-03-21 19:15

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Представление в URL')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'indexes': [models.Index(django.db.models.functions.text.Upper('title'), name='section_title_upper'), models.Index(django.db.models.functions.text.Upper('slug'), name='section_slug_upper')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Представление в URL')),
                ('annotation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Содержимое поста')),
                ('picture', models.ImageField(blank=True, upload_to='posts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Изображение')),
                ('status', models.CharField(choices=[('PUBLISHED', 'Опубликовано'), ('DRAFT', 'Черновик')], default='DRAFT', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Опубликован')),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Обновлен')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='Зафиксирован')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_posts', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('-created_at',),
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='blog_post_created_d633e5_brin'), models.Index(django.db.models.functions.text.Upper('title'), name='post_title_upper'), models.Index(django.db.models.functions.text.Upper('slug'), name='post_slug_upper')],
            },
        ),
    ]
