# Generated by Django 5.0.1 on 2024-03-15 16:55

import django.contrib.postgres.indexes
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Обновлен'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='blog_post_created_d633e5_brin'),
        ),
    ]
